---
title: "Exploring NFL Play-by-Play Data"
author: "Seth Goldman"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(skimr)
library(ggplot2)
library(lubridate)

pbp_2017 <- readRDS("pbp_2017")

```

```{r glimpse, echo = FALSE}
glimpse(pbp_2017)

```

```{r summary, echo = FALSE}
pbp_2017 %>% skim()

pbp_skim <- pbp_2017 %>% skim()
```

```{r variable_eda,echo = TRUE}
pbp_2017 %>% count(Passer) %>% arrange(desc(n))

pbp_2017 %>% count(Rusher)  %>% arrange(desc(n))

pbp_2017 %>% count(Receiver)  %>% arrange(desc(n))

pbp_2017 %>% count(Returner) %>% arrange(desc(n))

pbp_2017 %>% count(PlayType) %>% arrange(desc(n))

pbp_2017 %>% count(PassOutcome) %>% arrange(desc(n))

pbp_2017 %>% count(PuntResult)

pbp_2017 %>% count(PenalizedPlayer,PenalizedTeam) %>% arrange(desc(n))

pbp_2017 %>% count(Tackler1) %>% arrange(desc(n))

pbp_2017 %>% count(Tackler2) %>% arrange(desc(n))

pbp_2017 %>% filter(!is.na(Tackler2)) %>%  count(Tackler1,Tackler2) %>% arrange(desc(n))

pbp_2017 %>% count(RunLocation) %>% arrange(desc(n))

pbp_2017 %>% count(RunGap) %>% arrange(desc(n))

pbp_2017 %>% count(PassLocation) %>% arrange(desc(n))


```

### Explore EPA

```{r EPA, echo = TRUE}

pbp_2017 %>% arrange(desc(EPA)) %>% 
  select(Date,Passer,Receiver,Rusher,desc, EPA)

pbp_2017 %>% 
  group_by(Passer) %>% 
  summarise("total_epa" = sum(EPA)) %>% 
  arrange(desc(total_epa))


pbp_2017 %>% 
  filter(QBHit == 1) %>% 
  arrange(desc(EPA)) %>% 
  select(desc)

```


### Explore Play Type

```{r playtype, echo = TRUE}

pbp_2017 %>% 
  count(PlayType) %>% 
  ggplot(aes(x=PlayType, y = n)) +
  geom_point()+
  coord_flip() 


pbp_2017 %>% 
  filter(!PlayType %in% c("Timeout","Two Minute Warning", "Quarter End", "Half End", "End of Game")) %>% 
  count(posteam,PlayType) %>% 
  arrange(desc(n)) %>% 
  ggplot(aes(x=reorder(PlayType, n), y = n,col=PlayType)) +
  geom_point() +
  coord_flip()+
  facet_wrap(~posteam) +
  xlab("Play Type") +
  ylab("Plays")



```


```{r recept_rush, echp = TRUE}

# Explore Reception
pbp_2017 %>% 
  filter(PlayType %in% c("Pass","Run")) %>% 
  group_by(PlayType,Reception) %>% 
  tally()
# Explore RushAttempt
pbp_2017 %>% 
  filter(PlayType %in% c("Pass","Run")) %>% 
  group_by(PlayType,RushAttempt) %>% 
  tally()
```

```{r fourth_downs}

pbp_2017 %>% 
  filter(down == 4 & qtr < 5) %>% 
  ggplot(aes(x=qtr))+
  geom_bar(aes(fill=PlayType))



```


```{r drive_zoom_in}
pbp_2017 %>% 
  filter(GameID == GameID[[1]] & Drive == Drive[[1]]) %>% 
  select(time,TimeSecs,qtr,down,ydstogo,yrdln,yrdline100,ydsnet,posteam,DefensiveTeam,PlayType,Yards.Gained,AirYards,YardsAfterCatch,desc) 
```

```{r no_play}
# Explore Type of No Plays that are non-PassAttempts -- potentially penalties? (Confirmed)
pbp_2017 %>% 
  mutate("isPenalty" = case_when(grepl("Penalty", desc) ~ 1,
                                 grepl("PENALTY", desc) ~ 1,
                                 TRUE ~ 0)) %>%
  filter(PlayType == "No Play" & isPenalty == 0) %>% 
  select(PlayType,contains("Pen"),desc)


```


```{r receivers_analysis, echo=FALSE}
pbp_2017 %>% 
  filter(!is.na(Receiver)) %>% 
  group_by(Receiver,Receiver_ID) %>% 
  summarise("Receptions" = n(),
            "YardsGained" = sum(Yards.Gained),
            "YardsAfterCatch" = sum(YardsAfterCatch),
            "YPR" = YardsGained/Receptions,
            "YACPR" = YardsAfterCatch/Receptions) %>% 
  arrange(desc(YACPR)) 

pbp_2017 %>% 
  filter(!is.na(Receiver) & !is.na(down)) %>% 
  ggplot(aes(x=Yards.Gained)) +
  geom_density()+
  facet_wrap(ydstogo~down)

pbp_2017 %>% 
  filter(!is.na(Receiver) & !is.na(down)) %>% 
  mutate("yards_to_go_segment" = case_when(ydstogo == 0 ~ "0",
                                  ydstogo >= 1 & ydstogo < 4 ~ "short",
                                  ydstogo >= 4 & ydstogo < 8 ~ "short-medium",
                                  ydstogo >= 8 & ydstogo < 10 ~ "medium-long",
                                  ydstogo >= 10 ~ "long")) %>% 
  ggplot(aes(x=Yards.Gained)) +
  geom_density()+
  facet_grid(yards_to_go_segment~down) +
  ggtitle("Pass Yards Gained by Distance-to-go and Down",
          subtitle = "To-go could be a first down or a TD")


```

